server:
  port: 5000

spring:
  application:
    name: zuul-gateway-service
  zipkin:
    base-url: http://10.248.63.64:9411
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # 优先注册IP地址而不是hostname
    instance-id: zuul-gateway-container:${server.port}
  healthcheck:
    enabled: true # 启用健康检查,注意:需要引用spring boot actuator

management:
  security:
    enabled: false # 默认为true，改为false以便可以看到routes

